package com.unknown.guzhenren.registry;

import com.unknown.guzhenren.Guzhenren;
import net.minecraft.core.registries.Registries;
import net.minecraft.resources.ResourceKey;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.damagesource.DamageSource;
import net.minecraft.world.damagesource.DamageType;
import net.minecraft.world.entity.Entity;

//  Damage types are a datapack registry, so these are just keys -- the actual DamageType values are
//  generated by datagen/ModDatapackProvider and the bypass tags by ModDamageTypeTagsProvider.
public final class ModDamageTypes {

    private ModDamageTypes() {}

    //  Lifespan ran out: death of old age.
    public static final ResourceKey<DamageType> LIFESPAN_EXHAUSTED = key("lifespan_exhausted");

    //  Soul pool hit zero: 魂魄衰竭而亡.
    public static final ResourceKey<DamageType> SOUL_COLLAPSE = key("soul_collapse");

    //  Damage types are dynamic-registry entries, so a source can only be resolved against a live
    //  registry access. Take it straight off the entity: going via entity.level() would hand us a
    //  Level, which implements AutoCloseable, and every IDE would then nag about a resource we have
    //  no business closing.
    public static DamageSource source(Entity entity, ResourceKey<DamageType> type) {
        return new DamageSource(entity.registryAccess()
                .registryOrThrow(Registries.DAMAGE_TYPE)
                .getHolderOrThrow(type));
    }

    private static ResourceKey<DamageType> key(String name) {
        return ResourceKey.create(Registries.DAMAGE_TYPE,
                ResourceLocation.fromNamespaceAndPath(Guzhenren.MOD_ID, name));
    }
}
